//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detallePrestamo
    {
        [Required(ErrorMessage ="Debe agregar un ID al detalle")]
        public int id { get; set; }
        
        public int idLibro { get; set; }
        public int idPrestamo { get; set; }
        [Required(ErrorMessage = "Debe agregar una cantidad")]
        public int cantidad { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Prestamo Prestamo { get; set; }
    }
}
