//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Devoluciones
    {
        public int Id_devoluciones { get; set; }
        public int Id_prestamo { get; set; }
        [DataType(DataType.Date, ErrorMessage ="El formato de fecha no es valido")]
        public System.DateTime FechaDevolucion { get; set; }
        [Required(ErrorMessage ="Debe agregar una observación")]
        [StringLength(75)]
        public string Observaciones { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
