//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.detallePrestamo = new HashSet<detallePrestamo>();
        }
    
        public int Id_libro { get; set; }


        [Required(ErrorMessage ="Debe agregar el ISBN")]
        public int ISBN { get; set; }

        [Required(ErrorMessage ="El titulo del libro es requerido")]
        [StringLength(100)]
        public string Titulo { get; set; }


        [Required(ErrorMessage = "Debe agregar la edicion del libro")]
        [StringLength(50)]
        public string Edicion { get; set; }


        [DataType(DataType.Date, ErrorMessage ="El formato de fecha es incorrecto")]
        public System.DateTime Fecha_lanzamiento { get; set; }

        [Required(ErrorMessage ="Debe de agregar una descripción")]
        [StringLength(100)]
        public string Descripcion { get; set; }


        [Required(ErrorMessage = "Debe de agregar un idioma")]
        [StringLength(50)]
        public string Idioma { get; set; }


        
        public int NumeroPaginas { get; set; }


        [Required(ErrorMessage ="Debe agregar una cantidad")]
        public int Cantidad { get; set; }


        public int Id_categoria { get; set; }
        public int Id_autor { get; set; }
        public int Id_editorial { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePrestamo> detallePrestamo { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
