//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int Id_usuario { get; set; }
        [Required(ErrorMessage ="Debe agregar un nombre")]
        [StringLength(100)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Debe agregar un apellido")]
        [StringLength(100)]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Debe agregar un usuario")]
        [StringLength(50)]
        public string Usuario { get; set; }
        [Required(ErrorMessage ="Password requerido")]
        [StringLength(8)]
        [DataType(DataType.Password)]
        public string Pass { get; set; }
        public int Id_rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
